[package]
org = "ballerinax"
name = "temporal"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["temporal", "workflow", "orchestration"]
repository = "https://github.com/ballerina-platform/module-ballerinax-temporal"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[dependency]]
org = "ballerina"
name="workflow"
version="0.1.0"
repository="local"

[[platform.java21.dependency]]
path = "../native/build/libs/temporal-native-1.0.0-SNAPSHOT.jar"
groupId = "io.ballerina.stdlib"
artifactId = "temporal-native"
version = "1.0.0-SNAPSHOT"

[[platform.java21.dependency]]
path = "./lib/temporal-sdk-1.20.0.jar"

[[platform.java21.dependency]]
path = "./lib/temporal-serviceclient-1.20.0.jar"

[[platform.java21.dependency]]
path = "./lib/grpc-api-1.60.0.jar"

[[platform.java21.dependency]]
path = "./lib/grpc-context-1.60.0.jar"

[[platform.java21.dependency]]
path = "./lib/grpc-stub-1.60.0.jar"

[[platform.java21.dependency]]
path = "./lib/grpc-protobuf-1.60.0.jar"

[[platform.java21.dependency]]
path = "./lib/grpc-protobuf-lite-1.60.0.jar"

[[platform.java21.dependency]]
path = "./lib/grpc-core-1.60.0.jar"

[[platform.java21.dependency]]
path = "./lib/grpc-netty-shaded-1.60.0.jar"

[[platform.java21.dependency]]
path = "./lib/grpc-services-1.60.0.jar"

[[platform.java21.dependency]]
path = "./lib/protobuf-java-3.25.1.jar"

[[platform.java21.dependency]]
path = "./lib/protobuf-java-util-3.25.1.jar"

[[platform.java21.dependency]]
path = "./lib/jackson-core-2.15.3.jar"

[[platform.java21.dependency]]
path = "./lib/jackson-annotations-2.15.3.jar"

[[platform.java21.dependency]]
path = "./lib/jackson-databind-2.15.3.jar"

[[platform.java21.dependency]]
path = "./lib/jackson-datatype-jsr310-2.15.3.jar"

[[platform.java21.dependency]]
path = "./lib/jackson-datatype-jdk8-2.15.3.jar"

[[platform.java21.dependency]]
path = "./lib/tally-core-0.14.2.jar"

[[platform.java21.dependency]]
path = "./lib/guava-32.1.3-jre.jar"

[[platform.java21.dependency]]
path = "./lib/failureaccess-1.0.1.jar"

[[platform.java21.dependency]]
path = "./lib/perfmark-api-0.26.0.jar"