[package]
org = "ballerina"
name = "test_simple"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["temporal", "test"]
repository = "https://github.com/ballerina-platform/module-ballerinax-temporal"
license = ["Apache-2.0"]
distribution = "0.1.0-SNAPSHOT"

[platform.java21]
graalvmCompatible = true

[[dependency]]
org = "ballerinax"
name = "temporal"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "ballerina"
name="workflow"
version="0.1.0"
repository="local"
